baseURL = 'https://docs.printum.ru/'
languageCode = 'ru'
title = 'Printum'
languageName = 'ru'


disablePathToLower = true
# enableGitInfo = true

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]

# Book params

BookTheme = 'light' 
BookLogo = 'logo.png'
BookToC = true
BookSearch = true
# BookMenuBundle = '/menu'
# BookSection = 'docs'
# BookEditPath = 'edit/master/exampleSite'
