baseURL = 'https://docs.printum.ru/'
languageCode = 'ru-RU'
title = 'Printum'

disablePathToLower = true
# enableGitInfo = true

[params]

# Book params

BookTheme = 'light' 
BookLogo = 'logo.png'
BookToC = true
BookSearch = true
# BookMenuBundle = '/menu'
# BookSection = 'docs'
# BookEditPath = 'edit/master/exampleSite'
